version: '3.8'
services:
    mongo:
        image: mongo:latest
        container_name: mongo-c
        volumes:
            - mongo-data:/data/db
        ports:
            - 27017:27017
    server:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        container_name: server-c
        ports:
            - 3051:3051
        depends_on:
            - mongo
        volumes:
            - ./server:/app
            - /app/node_modules
        env_file:
            - ./server/.env.dev
        # environment:
        #     - PORT=3051
        #     - REDIS_URL=localhost
        #     - MONGO_DB_HOST=mongo
        #     - MONGO_DB_PORT=27017
        #     - MONGO_DB_NAME=messteenDEV
volumes:
    mongo-data:
